platformName: Android
#模拟器
platformVersion: 6.0.1 #8.0.0
deviceName: 1ec63518 #V3HBB18727512494
appname: starlink_install_v4.2.7_2020-08-26-16-15-19.apk
noReset: False
unicodeKeyboard: True
resetKeyboard: True
appPackage: org.xc.starlinkother
appActivity: org.xc.starlinkother.activity.StartActivity
ip: 127.0.0.1
port: 4723
